docs/upgrade_kits/ankle_for_stairs/support.md
As in most cases whole body software that exploit also the legs only uses URDF models and this is a modification that for now was only installed on internal IIT robots, I think it is ok to just specify that an appropriate model needs to be used, without further details.
=> Add software details for KIT_007

.github/workflows/gh-pages.yml, .github/workflows/update-sw-distros.yml
This PR allows for automatically triggering the build of gh-pages as a result of a SW distros update.
=> Trigger documentation via dispatching

docs/icub_operating_systems/other-machines/generic-machine.md
A few changes: 
* Fixed a few typos
* Remove manual installation of qt packages, that has not been necessary since 2014 
* Remove manual installation of OpenCV 2.4.8, not necessary anymore on modern distros 
* Add links for bashrc for both the superbuild and non-superbuild variant
* Fixed rendering on GitHub
* Change Debian references from wheezy to buster
=> Cleanup icub_operating_systems/other-machines/generic-machine.md file

docs/icub_operating_systems/other-machines/generic-machine.md
This was something that we noticed with @Iaxama, but I did not put this with https://github.com/icub-tech-iit/documentation/pull/72 as I am not sure on this change, so I would prefer to have @mbrunettini opinion before merging. 
As far as we can see, configuring the laptop to use the NTP server of icub-server could be useful to ensure that icub-head and iCub's laptop use the same time, but perhaps we are missing something.
=> Also configure the NTP support for iCub laptop instructions

docs/icub_r1_calibration_types/icub_r1_calibration_types.md, docs/icub_sw.md, mkdocs.yml
📝 As per title the old wiki page migrated is  : 
- https://wiki.icub.org/wiki/Calibration_types_available_on_iCub_and_R1_robots
➕ Also added calibration type 8 and 9
cc @ale-git @maggia80 @traversaro
=> added doc on calib types

docs/stylesheets/extra.css, mkdocs.yml
This PR introduces extra CSS to let the central column be displayed larger than the default width.
=> Enlarge central column

docs/javascripts/config.js, mkdocs.yml
This PR enables the use of MathJax as per instructions in https://squidfunk.github.io/mkdocs-material/reference/mathjax.
=> Enable MathJax

docs/ft_sensors/change_of_frame_accelerometer.md, docs/ft_sensors/index.md, docs/ft_sensors/onboard_imu.md, mkdocs.yml
This PR integrates #105 with the [study][1] done by @traversaro on the change of frame for the accelerometer measurements.
This was made possible thanks to the MathJax plugin introduced in #107.
[1]: http://mathb.in/50168
=> Add study on change of frame

docs/sw_installation/linux_binaries.md
A back quote was present in the line associated to the public key, causing potential errors when copy pasting.
=> Fixed back quote in public key

docs/icub_operating_systems/pc104/the-icub-live-installation.md
This is just a proposal to be discussed. 
While reading the pc104 documentation, I noticed that we continue do document how to burn the icub-live 5.0 image, for which however we do not provide any download. As the documentation is already relatively complex, I was wondering if we could just drop the instructions on how to burn the icub-live 5.0 docs. If we ever **really need them**, they can be found in git history or just by looking on Google for this PR. : )
=> [PROPOSAL] Remove instructions on how to burn icub-live 5.0 image

docs/icub_operating_systems/pc104/icub-live-32bits.md, docs/icub_operating_systems/pc104/icub-live.md, mkdocs.yml
This PR includes instructions to build a 32 bits version of the more recent iCub LIVE OS. 
cf https://github.com/robotology/icub-tech-support/issues/1106
=> Add guide for 32bits build of iCub LIVE

docs/icub_operating_systems/icubos/installation-from-image.md
I recently installed a iCubOS 8 image (based on Ubuntu 20.04) and talking with @davidelasagna it turned out that the Bluetooth option is not strictly necessary, so I modified the link to clarify that. Furthermore, I also added a link to the documentaiton on how to install YARP/iCub software, as this is the natural following step after you installed a new image.
=> Clarify steps after installation on icub-head from pre-built image

scripts/sw-distros/template_index.md
This is a possible variation of the explanation of our distro workflow following up on @traversaro 's proposal.
=> Distro naming convention relies on patch number

docs/icub_operating_systems/other-machines/icub-server-laptop.md
Following the installation procedure and without this step it is impossible to start yarpserver from yarpmanager GUI (keeps asking for the password on the terminal).
=> ssh-copy-id between icubsrv and icubsrv itself

docs/icub_operating_systems/icubos/installation-from-scratch.md
Since https://github.com/icub-tech-iit/documentation/pull/84 the documentation was targeting Ubuntu 20.04 (focal), but this specific step was still targeting Xenial (16.04). I changed it to target focal, with an additional sentence to avoid to create problems even if in the future we do not update it again.
=> Fix instruction on installing http://www.icub.org/ubuntu repo on iCubOS

docs/icub_versions/index.md
Hi @maggia80, @Fabrizio69 
We need to eventually account for iCub v3.0 too.
This is required to keep track of version v3.1 with the new head.
Ref.: #225.
cc @mfussi66
=> Add iCub `v3.x`

docs/hands/hands_mk5.md
For more backward compatibility and since in the elbow we have just one joint I would remove the `_pitch` suffix
(in `ergoCub` urdfs is already like that)
cc @pattacini @Lawproto @salvi-mattia @Mick3Lozzo @fiorisi @traversaro @mfussi66
=> Fix elbow joint name in hand mk5

docs/icub_kinematics/icub-model-naming-conventions/icub-model-naming-conventions.md
=> Add sensor naming convention

docs/hands/hands_mk5_coupling.md
This updates the `Hand Mk5 Coupling Laws` documentation page according to #257.
Specifically:
- it fixes $q_{1off}$ of the pinky finger
- fix expression of $q_2$ as a function of $q_1$
Rendering has been tested on `gitpod`.
Fixes #257
=> Update Hand MK5 coupling laws

docs/robot_sensors/ergocub_sensors.md, docs/robot_sensors/icub2.7_sensors.md, docs/robot_sensors/icub3_sensors.md, docs/robot_sensors/index.md
This PR is a first attempt at documenting all the sensor interfaces available on the robots iCub2.7, iCub3, ergoCub.
There is a page for each robot, with tables for each robot part. The rows contain info about the sensor involved, and which port to use with YARP to access the data.
To browse the documentation in my fork, you can use this Gitpod snapshot: https://gitpod.io/new/#snapshot/5e5df273-9670-4e69-8546-e36a27cdf7e5 .
Just do a `mkdocs serve` in the VSCode terminal, and click on the link to be redirected to the rendered doc page.
=> Add sensor tables for robots

.github/workflows/gh-pages.yml, .github/workflows/test-pr.yml, .gitpod.Dockerfile, README.md, docs/icub_robot_configuration/devices_configuration/devices_configuration.md, mkdocs.yml
We can use from `mkdocs@v1.5.0`:
- `mkdocs get-deps` to parse `mkdocs.yml` and determine the required extensions.
- rely on `not_in_nav` section to omit files.
=> Use mkdocs@v1.5.0

docs/icub_microphones/icub_microphones.md
During the maintenance tests of `iCubSingapore01` I find this typo error on [iCub Microphones](https://icub-tech-iit.github.io/documentation/icub_microphones/icub_microphones/?h=micr) page.
This PR fix this incorrect command.
cc @sgiraz
=> Fix an incorrect command on icub_microphones.md

docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
For AMO-based robots, one can disable the AMO sensors outright in favor of the motor quadrature encoders.
cc @danielepucci @ale-git @traversaro
=> Document a special case of Calibration Type 10

docs/icub_operating_systems/icubos/user-env.md, docs/icub_operating_systems/pc104/the-icub-live-details.md
This closes https://github.com/icub-tech-iit/documentation/issues/324
=> Update the iCub user enviroment documentation

docs/icub_robot_calibration/icub3-stator-rotor-autocalibration.md
In the PR https://github.com/robotology/icub-firmware/pull/466 we changed the default value from 0 to 0xffff because 0 is one possible value for the offset.
cc @MSECode
=> Update the stator-rotor calibration with the default value

docs/ergoCub1_wiring/ergoCub1_1.md
We've updated links under **ergoCub1_wiring** and also added pdfs of the schematics of `eCub1.1 S/N:002`
cc @pattacini @sgiraz
=> Fix hyperlinks under ergoCub1_wiring folder

docs/ergoCub1_wiring/ergoCub1_1.md, docs/ergoCub1_wiring/ergoCub1_2.md
I've updated links under ergoCub1_wiring and I separated the ergoCub1.1 (SN001) and ergoCub1.2 (SN002) pdfs
cc @pattacini
=> fix hyperlinks ergoCub1.1 & ergoCub1.2 - wiring folder

docs/temperature_sensors/software/dataflow.md
I just added the following table to help diagnose the error that occurred in the motor temperature reading.
Please see the ticket https://github.com/robotology/icub-tech-support/issues/1809#issuecomment-2110651763
cc @MSECode
=> Motor temperature: add table for error raw value conversion

docs/icub_operating_systems/icubos/jetpack.md
The existing link points to the Boson Xavier page, not the Boson Orin page.
fyi @GiulioRomualdi
=> jetpack: Fix link to Boson for FRAMOS Orin NX page

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitpod.yml, README.md
This PR refactors the infrastructure to favor Codespaces and remove Gitpod.
=> From Gitpod to GH Codespaces

docs/sw_installation/conda_binaries.md
Same motivations as in https://github.com/robotology/robotology-superbuild/pull/1653 . 
In a nutshell:
* Since conda 23.10 (released on November 2023), the `libmamba` solver is the default solver (see https://conda.org/blog/2023-11-06-conda-23-10-0-release/), and that should give more and less the same performances of the `mamba` command, without the confusion between `conda` and `mamba` for new users.
* `mambaforge` is deprecated since July 2024 and will be removed in January 2025 (see https://github.com/conda-forge/miniforge/commit/362b0c4aa285d8af9cafc59b0b1eaa4fa6fb0dad). As now `miniforge` also contains `mamba`, users can just install `miniforge` in place of `mambaforge` and get exactly the same functionality.
So this PR changes all the instances of `mambaforge` to `miniforge` and of …
=> Update conda instructions to use miniforge and conda instead of mambaforge and mamba

docs/icub_operating_systems/pc104/icub-live.md
Modern Debian are not tested in CI, but probably they work fine, as any other modern Linux distro.
=> Specify that we stopped supporting Debian <= 10 in superbuild

docs/icub_operating_systems/other-machines/generic-machine.md
These repos and packages have been deprecated in 2023 (see https://github.com/orgs/robotology/discussions/612 and https://github.com/orgs/robotology/discussions/653). 
The required dependencies are installed as part of the robotology-superbuild installation, so we do not need to change this instructions with anything else.
=> generic-machine docs: Do not suggest to use the icub.eu apt repo and install icub-common repo

docs/icub_operating_systems/icubos/installation-from-ansible-playbook.md, docs/icub_operating_systems/icubos/installation-from-scratch-22.04.md, docs/icub_operating_systems/other-machines/generic-machine-22.04.md, mkdocs.yml
check https://github.com/icub-tech-iit/tickets/issues/2292#issuecomment-2548568290
=> added 22.04 page and ansible playbook guide

docs/icub_operating_systems/icubos/install-librealsense.md
This PR fixes https://github.com/icub-tech-iit/documentation/issues/378.
I updated the documentation about how the librealsense is installed depending on the Jetpack version (I divided it into two sections). 
cc @Nicogene @traversaro
=> Update librealsense installation instructions

docs/icub_operating_systems/icubos/jetpack.md, docs/icub_operating_systems/icubos/setup-ergocub-screen.md, mkdocs.yml
This pull request includes updates to the documentation related to the `ergocub-head` setup process. The most important changes involve adding a new guide for setting up the ergoCub screen and updating the navigation to include this new guide.
Documentation updates:
* [`docs/icub_operating_systems/icubos/jetpack.md`](diffhunk://#diff-a02cdf58276b80d0bf376a87fc7789a940041cc2295c2fee9afbc67e207047a6R146): Added a new link to the "Setup ergoCub screen" guide.
* [`docs/icub_operating_systems/icubos/setup-ergocub-screen.md`](diffhunk://#diff-74d5d699e529ef60d91a361da1c0562aa54d8b1a69041e0fb45066004618687aR1-R67): Created a comprehensive guide for setting up the ergoCub screen, including instructions for hiding the Ubuntu bar, changing the desktop wallpaper, and cleaning the icons from the …
=> Add documentation to setup the screen of the ergocub-head

docs/icub_firmware/fw_toolchain/installing_keil.md
As of early 2025, the steps required to activate a MDK Community (non-commercial) license do not require to receive a product serial number but just to list a MDK Community License server, so I (hopefully) clarified the wording.
=> FW docs: Clarify the steps require to activate a MDK community license

docs/ergoCub1/ergoCub1-joints.md
The PR updates:
- The range of motion of the wrist roll and wrist pitch.
- The range of motion of the index ab/adduction.
Associated documentation:
- Wrist: [robot configuration file](https://github.com/robotology/robots-configuration/blob/3be388a8bbb7e1b588657ec7ac24feb8509a1c33/ergoCubSN002/hardware/mechanicals/left_arm-eb31-j4_6-mec.xml#L22)
- Index: CAD model
=> Update ergoCub1 wrist range of motion

docs/ergoCub1/ergoCub1-joints.md
I have reviewed the range of motion (RoM) of the Hip Pitch joint and updated it following a verification of both the robot and the CAD model.  
The highlighted areas below indicate the hard stop locations (thanks @AntonioConsilvio).
=> Update ergoCub1 Hip Roll RoM

docs/upgrade_kits/ankle_for_stairs/support.md, docs/upgrade_kits/backpack/support.md, docs/upgrade_kits/differential_neck_pulley/support.md, docs/upgrade_kits/eyes/support.md, docs/upgrade_kits/hands/support.md, docs/upgrade_kits/head_4k/support.md, docs/upgrade_kits/index.md, docs/upgrade_kits/torso_capacitors/support.md, docs/upgrade_kits/upperarm_cover_icub2_5/support.md
The html syntax `<center>` works only with html
We can use `<figure>` for native markdown, instead.
cc @Nicogene
=> Fix syntax for some centered images

docs/temperature_sensors/software/dataflow.md
This PR adds some fixes on the documentation related to this PR: https://github.com/robotology/icub-firmware/pull/606, which differentiates the i2c communication error from the overheating error making 2 separates errors sent to the GUI.
=> Update TDB doc after fw chnage for i2c comm error
