icub-tech-iit/documentation

- .github/workflows/test-pr.yml
This PR adds up a CI for building/testing PR's docs.
> CI: test PR's

- docs/icub.md
- docs/icub_versions/index.md
- mkdocs.yml
- see https://github.com/icub-tech-iit/fix/issues/509
> added iCub versions table 

- docs/upgrade_kits/hands/support.md
> modify bom table in existing ukit

- docs/upgrade_kits/differential_neck_pulley/support.md
- docs/upgrade_kits/eyes/support.md
- docs/upgrade_kits/hands/support.md
- docs/upgrade_kits/index.md
- docs/upgrade_kits/torso_capacitors/support.md
- docs/upgrade_kits/upperarm_cover_icub2_5/support.md
This PR addresses https://github.com/icub-tech-iit/documentation/issues/17#issuecomment-663496153.
> Make UKITs Ordering via Ids Explicit

- docs/upgrade_kits/upperarm_cover_icub2_5/support.md
> Fix warning in upperarm ukit

- docs/upgrade_kits/upperarm_cover_icub2_5/support.md
> Removed WIP warning for upper arms UKIT 

- docs/upgrade_kits/differential_neck_pulley/support.md
added "onboard" line in the initial table
> Added "available onboard"

- docs/icub_hw.md
- docs/icub_sw.md
- docs/index.md
- mkdocs.yml
This PR introduces the summary page where to collect SW info.
> Refactoring to add up SW section

- docs/icub_wiring/icub1_x.md
- docs/icub_wiring/icub2_x.md
- docs/icub_wiring/index.md
- mkdocs.yml
Added the iCub Wiring section (porting from the old page http://wiki.icub.org/wiki/Electrical_wiring)
This is just a first step forward...
> iCub Wiring section

- docs/icub_tendons/cabling_V2.md
> substituted IITCODE for thumb oppose sheath

- scripts/sw-distros/template_index.md
> Add pointer to distros announcements

- docs/icub_operating_systems/icubos/bios.md
I'll add some screenshots of the BIOS for showing the right configuration of these parameters.
> adding how to set the max power

- README.md
I typically use the local workflow documented in this PR, so I thought it could useful to document it as an alternative to Cloud IDEs.
> Add documentation on how to render the website locally 

- docs/icub_microphones/icub_microphones.md
- mkdocs.yml
✏️ I started adding documentation about microphones; at this stage, the info I migrated are picked up from : 
- https://github.com/robotology/community/discussions/461#discussioncomment-230247
- [robotology/community#461 (reply in thread)](https://github.com/robotology/community/discussions/461#discussioncomment-266914) 
We can discuss here on what to add/change  📝 
cc @pattacini @traversaro
> Adding Microphones documentation

- docs/configure_static_ip/configure-static-ip.md
- docs/icub_sw.md
- mkdocs.yml
as requested [here](https://github.com/icub-tech-iit/documentation/issues/85), the doc title has been changed.
cc @mbrunettini @traversaro
> changed doc title as req in #85

- docs/icub_wiring/icub2_x.md
I just fixed the links to repository
> Talking head wiring - links were leading nowhere

- docs/icub_operating_systems/icubos/bluetooth.md
It reports the info listed in https://github.com/robotology/icub-main/pull/727.
> Update the bluetooth related instructions considering BCB bluetooth

- docs/icub_operating_systems/icubos/bluetooth.md
It addresses https://github.com/icub-tech-iit/documentation/issues/118
cc @pattacini @mbrunettini @davidelasagna @violadelbono @Uboldi80
> Improve the battery Bluetooth documentation

- .github/workflows/update-sw-distros.yml
Create a PR instead of a direct commit.
> Create PR for updating Distros Docs

- .github/workflows/check-links.yml
This PR introduces links checking as discussed in #94.
cc @traversaro
> Checking links

- docs/icub_operating_systems/icubos/user-env.md
In particular, move the things that needs to be done at the beginning of the section, and only after the precise instructions provide a motivation for it.
Fix https://github.com/icub-tech-iit/documentation/issues/144 .
> Clarify "How to setup the enviroment properly" section

- docs/icub_operating_systems/icubos/user-env.md
> User env section improved

- docs/icub_ros/index.md
- mkdocs.yml
Add documentation for publishing joints state to ROS, based on https://github.com/robotology/community/discussions/545
> Add doc for using ROS

- docs/icub_hw.md
adding links of the main hw repos
> adding cad-mechanics-public link

- docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
Calibration Type 10 specification and brief AMO magnetic target descriptio added.
> Added Type 10 calibration description

- .github/workflows/gh-pages.yml
- .github/workflows/test-pr.yml
- mkdocs.yml
This PR adds up new navigation features as per https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation.
> New `mkdocs-material` navigation features

- README.md
- docs/icub_operating_systems/icubos/installation-from-scratch.md
- docs/icub_operating_systems/other-machines/generic-machine.md
- docs/icub_robot_calibration/img/chess-2.html
- docs/sw_installation/check_your_installation.md
- docs/sw_installation/linux_binaries.md
- docs/sw_installation/linux_from_sources_manual.md
changed references from icub.org to icub.eu
> from icub.org to icub.eu

- docs/icub_operating_systems/icubos/icubos.md
- docs/icub_operating_systems/other-machines/icub-server-os.md
> Fix typo lastet/latest

- .github/workflows/gh-pages.yml
- .github/workflows/test-pr.yml
As per the title.
cc @traversaro
> Fix `pygment` dep

- docs/sw_installation/linux_binaries.md
> Jammy cosmetics

- mkdocs.yml
This PR adds up the [Automatic light / dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=dark+light#automatic-light-dark-mode).
> Light/Dark Mode

- docs/icub_kinematics/icub-shoulders-range-of-motion/icub-shoulders-range-of-motion.md
Ref.: https://github.com/orgs/robotology/discussions/602.
> Fix shoulders' constraints equation

- docs/hands/img/placeholder.txt
- docs/hands/index.md
- docs/icub_hw.md
> Prepare infrastructure for hand Mk5 documentation.

- docs/sw_installation/conda_binaries.md
- docs/sw_installation/linux_binaries.md
- mkdocs.yml
> Add conda binary installation and deprecate Deb packages

- docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
Update calibration14 documentation with procedure to follow for finding correct values of calibration parameters to be set in the configuration files
> Update documentation calib14

- docs/icub_operating_systems/icubos/networking.md
- docs/icub_versions/index.md
Fix #167, #176.
For a better back-to-back comparison that rules out spaces, click on:
- https://github.com/icub-tech-iit/documentation/pull/296/files?diff=split&w=1.
> Fix #167, #176

- docs/hands/hands_mk5.md
This wants to solve the issue https://github.com/icub-tech-iit/ergocub-software/issues/168.
> fixing thumb joint value

- docs/hands/hands_mk5.md
As of https://github.com/icub-tech-iit/ergocub-software/issues/168#issuecomment-1710647068.
> fixing thumb distal joint value

- docs/sw_versioning_table/index.md
> Fix index.md

- docs/hands/hands_mk5_coupling.md
As of https://github.com/icub-tech-iit/documentation/issues/307#event-10343328232.
> correcting Mk5.1 length parameters

- .github/workflows/check-links.yml
- docs/icub_operating_systems/other-machines/icub-server-from-scratch.md
- docs/icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
- docs/robot_sensors/yarp_nws_convention.md
- docs/upgrade_kits/head_4k/support.md
- scripts/linkchecker/linkcheckerrc
> Fix external links – Stint 2

- docs/upgrade_kits/head_4k/support.md
- scripts/linkchecker/linkcheckerrc
> Fix external links – Stint 3

- docs/upgrade_kits/head_4k/support.md
- scripts/linkchecker/linkcheckerrc
This PR fixes the problem reported in https://github.com/icub-tech-iit/documentation/pull/316#discussion_r1325831760.
> Fix external links – Stint 4

- docs/robot_sensors/yarp_nws_convention.md
As per title, little correction added since a RGBD Sensor client exists.
> Update yarp_nws_convention.md by adding RGBDSensorClient

- docs/ergoCub1_wiring/ergoCub1_2.md
Updated harness and logic links of ergoCub1.2 - documentation
> Updated ergoCub1.2 links

- docs/icub_operating_systems/icubos/jetpack.md
This PR adds the official documentation to install and configure the Jetson Orin NX board
> Add Orin NX installation instructions

- docs/sw_installation/linux_from_sources_superbuild.md
> Fix link in the superbuild installation instructions

- docs/icub_versions/index.md
Added v2.4 version used for new iCubGrenoble01
cc: @Nicogene @maggia80 @AntonioAzocar
> Update index.md: new iCub version table

- docs/icub_firmware/firmwareupdater/firmwareupdater.md
This PR extends the [FirmwareUpdater Walkthrough](https://icub-tech-iit.github.io/documentation/icub_firmware/firmwareupdater/firmwareupdater/) by including a troubleshooting section that reports on the recommendations @AntonioConsilvio listed down in https://github.com/robotology/icub-tech-support/issues/2041#issuecomment-2684494558.
Further recommendations may be added later.
> FWUpdater Troubleshooting

- docs/ergocub_versions/index.md
As per title
cc @fiorisi @Fabrizio69 @maggia80
> Update ergocub versioning table adding v1.3.1

- docs/icub_firmware/Automatic_Firmware_Update_Runbook/Automatic_Firmware_Update_Runbook.md
- docs/icub_firmware/automatic_firmware_update_runbook/automatic_firmware_update_runbook.md
- docs/icub_firmware/index.md
- mkdocs.yml
Created the documentation for the conducting the automatic firmware update on a Robot or any setup using the readily available script on a part or particular board or excluding certain board/part by updating all or various combination and also using the python script with more flexibility and options based on user need.  
https://github.com/sksubiit/documentation/blob/master/docs/icub_firmware/Automatic_Firmware_Update_Runbook/Automatic_Firmware_Update_Runbook.md
> Automatic_Firmware_Update_Runbook documentation

- docs/icub_firmware/automatic_firmware_update_runbook/automatic_firmware_update_runbook.md
This is the updated documentation for including the parallel update process with the firmware updater using automated script
> parallel update commands
